#ifndef XPARAMETERS_H
#define XPARAMETERS_H
/* Only what platform_ids.h (classic flow) needs to resolve. */
#define XPAR_ADC_CHANNEL_SWITCH_ADC_SWITCH_DEVICE_ID 0
#define XPAR_DDS_H2C_SWITCH_DEVICE_ID   1
#define XPAR_ADC_CHANNEL_SELECT_DEVICE_ID 0
#define XPAR_AXI_GPIO_DYNAMIC_CLK_DEVICE_ID 1
#define XPAR_CLOCK_COUNTER_DEVICE_ID    2
#define XPAR_AXI_GPIO_DDS1DDS2_DEVICE_ID 3
#define XPAR_SYSREF_CONTROLL_DEVICE_ID  4
#define XPAR_QUAD_SPI_LMK_DEVICE_ID     0
#define XPAR_QUAD_SPI_ADC_LMX_DEVICE_ID 1
#define XPAR_QUAD_SPI_DAC_LMX_DEVICE_ID 2
#define XPAR_CLK_WIZ_ADC_BASEADDR       0xA0070000
#define XPAR_CLK_WIZ_DAC_BASEADDR       0xA0080000
#define XPAR_XRFDC_0_DEVICE_ID          0
#define XPAR_XRFDC_0_BASEADDR           0xA0000000
#define XPAR_XGPIOPS_0_DEVICE_ID        0
#define XPAR_XGPIOPS_0_INTR             48
#define XPAR_SCUGIC_0_DEVICE_ID         0
#endif
