/******************************************************************************
 *
 * platform_ids.h
 *
 * Single point of translation between the application and the hardware
 * identifiers generated by the BSP.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * Vitis 2023.2 introduced the System Device Tree (SDT) flow, which Vitis
 * 2025.2 uses by default (the build passes -DSDT). Under SDT the BSP no longer
 * emits XPAR_<instance>_DEVICE_ID for most drivers, and the driver lookup /
 * initialise entry points take a BASE ADDRESS instead of a device index:
 *
 *     classic (<= 2023.1)              SDT (>= 2023.2)
 *     ---------------------------      ---------------------------------
 *     XGpio_Initialize(p, DEV_ID)      XGpio_Initialize(p, BASEADDR)
 *     XSpi_LookupConfig(DEV_ID)        XSpi_LookupConfig(BASEADDR)
 *     XAxisScr_LookupConfig(DEV_ID)    XAxisScr_LookupConfig(BASEADDR)
 *     XRFdc_LookupConfig(DEV_ID)       XRFdc_LookupConfig(BASEADDR)
 *     XGpioPs_LookupConfig(DEV_ID)     XGpioPs_LookupConfig(BASEADDR)
 *     XScuGic_LookupConfig(DEV_ID)     XScuGic_LookupConfig(BASEADDR)
 *
 * Rather than scatter #ifdef SDT through main.c, every identifier the
 * application needs is resolved once, here. main.c uses the HW_* names only.
 *
 * The instance names (ADC_CHANNEL_SWITCH_ADC_SWITCH, QUAD_SPI_LMK, ...) come
 * from the Vivado block design and are identical in both flows, so only the
 * SUFFIX changes. Where a macro could plausibly carry more than one name, a
 * #if defined() chain picks whichever the BSP actually emitted, and #error
 * fires at compile time if none of them exist -- that is deliberate: a silent
 * fallback to a wrong address is far worse than a build failure.
 *
 ******************************************************************************/

#ifndef SRC_PLATFORM_IDS_H_
#define SRC_PLATFORM_IDS_H_

#include "xparameters.h"

/*---------------------------------------------------------------------------
 * PL peripherals: AXI GPIO, AXI4-Stream Switch
 *
 * NOTE: the baseline main.c contained a LOCAL redefinition of
 *       XPAR_SYSREF_CONTROLL_BASEADDR / _DEVICE_ID. The SDT BSP defines
 *       XPAR_SYSREF_CONTROLL_BASEADDR itself, which produced a "redefined"
 *       warning. The application no longer shadows BSP hardware config.
 *---------------------------------------------------------------------------*/
#ifdef SDT

  #define HW_AXIS_SWITCH_ID        XPAR_ADC_CHANNEL_SWITCH_ADC_SWITCH_BASEADDR
  #define HW_DDS_H2C_SWITCH_ID     XPAR_DDS_H2C_SWITCH_BASEADDR
  #define HW_ADC_SELECT_GPIO_ID    XPAR_ADC_CHANNEL_SELECT_BASEADDR
  #define HW_DYN_CLK_GPIO_ID       XPAR_AXI_GPIO_DYNAMIC_CLK_BASEADDR
  #define HW_CLK_COUNTER_GPIO_ID   XPAR_CLOCK_COUNTER_BASEADDR
  #define HW_DDS_GPIO_ID           XPAR_AXI_GPIO_DDS1DDS2_BASEADDR
  #define HW_SYSREF_GPIO_ID        XPAR_SYSREF_CONTROLL_BASEADDR

  #define HW_QSPI_LMK_ID           XPAR_QUAD_SPI_LMK_BASEADDR
  #define HW_QSPI_ADC_LMX_ID       XPAR_QUAD_SPI_ADC_LMX_BASEADDR
  #define HW_QSPI_DAC_LMX_ID       XPAR_QUAD_SPI_DAC_LMX_BASEADDR

#else   /* classic XPAR_*_DEVICE_ID flow (Vitis <= 2023.1) */

  #define HW_AXIS_SWITCH_ID        XPAR_ADC_CHANNEL_SWITCH_ADC_SWITCH_DEVICE_ID
  #define HW_DDS_H2C_SWITCH_ID     XPAR_DDS_H2C_SWITCH_DEVICE_ID
  #define HW_ADC_SELECT_GPIO_ID    XPAR_ADC_CHANNEL_SELECT_DEVICE_ID
  #define HW_DYN_CLK_GPIO_ID       XPAR_AXI_GPIO_DYNAMIC_CLK_DEVICE_ID
  #define HW_CLK_COUNTER_GPIO_ID   XPAR_CLOCK_COUNTER_DEVICE_ID
  #define HW_DDS_GPIO_ID           XPAR_AXI_GPIO_DDS1DDS2_DEVICE_ID
  #define HW_SYSREF_GPIO_ID        XPAR_SYSREF_CONTROLL_DEVICE_ID

  #define HW_QSPI_LMK_ID           XPAR_QUAD_SPI_LMK_DEVICE_ID
  #define HW_QSPI_ADC_LMX_ID       XPAR_QUAD_SPI_ADC_LMX_DEVICE_ID
  #define HW_QSPI_DAC_LMX_ID       XPAR_QUAD_SPI_DAC_LMX_DEVICE_ID

#endif /* SDT */

/*---------------------------------------------------------------------------
 * DDS / host-stream switch (DDS_H2C_switch, 2 SI -> 1 MI) -- PORT WIRING.
 *
 * Which slave port carries which stream is a property of the bitstream, not
 * of the software, so it lives here with the other hardware facts. Taken from
 * the hardware handoff in H2C_pcie_control.xsa (design_1.hwh, instance
 * DDS_H2C_switch):
 *
 *     S00_AXIS  <-  External_Interface_H2C_data_in  host / GNU Radio (QDMA H2C)
 *     S01_AXIS  <-  dds_compiler_2 / M_AXIS_DATA     DDS compiler
 *     M00_AXIS  ->  axis_broadcaster_1 -> DAC tiles
 *
 * The baseline's comment said "SI 0 (DDS)" and every layer above it inherited
 * that, so DDS and host were swapped end to end: the DAC booted on the (idle)
 * host stream, and selecting "host" played the DDS. main.c converts the
 * logical PCIE_DAC_SRC_* values to these ports in ONE function; if the block
 * design is ever rewired, these two lines are the only thing to change.
 *---------------------------------------------------------------------------*/
#define HW_DAC_SW_SI_HOST          0U
#define HW_DAC_SW_SI_DDS           1U

/*---------------------------------------------------------------------------
 * Clocking Wizard - raw AXI4-Lite access, no driver, BASEADDR in both flows.
 *---------------------------------------------------------------------------*/
#define HW_CLK_WIZ_ADC_BASE        XPAR_CLK_WIZ_ADC_BASEADDR
#define HW_CLK_WIZ_DAC_BASE        XPAR_CLK_WIZ_DAC_BASEADDR

/*---------------------------------------------------------------------------
 * RF Data Converter
 *---------------------------------------------------------------------------*/
#ifdef SDT
  #if   defined(XPAR_XRFDC_0_BASEADDR)
    #define HW_RFDC_ID             XPAR_XRFDC_0_BASEADDR
  #elif defined(XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR)
    #define HW_RFDC_ID             XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR
  #else
    #error "platform_ids.h: no RFDC base address in xparameters.h."
  #endif
#else
  #define HW_RFDC_ID               XPAR_XRFDC_0_DEVICE_ID
#endif

/* Raw register access (rfdc_cmd.c) always needs the real aperture base,
 * regardless of which flow supplies the lookup handle. */
#if   defined(XPAR_XRFDC_0_BASEADDR)
  #define HW_RFDC_BASE             XPAR_XRFDC_0_BASEADDR
#elif defined(XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR)
  #define HW_RFDC_BASE             XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR
#else
  #error "platform_ids.h: no RFDC base address in xparameters.h."
#endif

/*---------------------------------------------------------------------------
 * PS GPIO (LMK lock indicator)
 *---------------------------------------------------------------------------*/
#ifdef SDT
  #if   defined(XPAR_XGPIOPS_0_BASEADDR)
    #define HW_GPIOPS_ID           XPAR_XGPIOPS_0_BASEADDR
  #elif defined(XPAR_PSU_GPIO_0_BASEADDR)
    #define HW_GPIOPS_ID           XPAR_PSU_GPIO_0_BASEADDR
  #else
    #error "platform_ids.h: no PS GPIO base address in xparameters.h."
  #endif
#else
  #define HW_GPIOPS_ID             XPAR_XGPIOPS_0_DEVICE_ID
#endif

/*---------------------------------------------------------------------------
 * Generic Interrupt Controller
 *
 * IMPORTANT (silent-failure class bug):
 * The baseline passed XPAR_SCUGIC_0_DEVICE_ID to XScuGic_LookupConfig(). Some
 * SDT BSPs still emit that macro for backward compatibility, so this COMPILES
 * CLEANLY under 2025.2 -- but SDT's XScuGic_LookupConfig() matches on BASE
 * ADDRESS. A device index of 0 matches nothing, LookupConfig() returns NULL,
 * and the very next line dereferences IntcConfig->CpuBaseAddress: a data abort
 * at boot, with no compiler warning anywhere. Resolved by base address here.
 *---------------------------------------------------------------------------*/
#ifdef SDT
  #if   defined(XPAR_SCUGIC_0_BASEADDR)
    #define HW_SCUGIC_ID           XPAR_SCUGIC_0_BASEADDR
  #elif defined(XPAR_XSCUGIC_0_BASEADDR)
    #define HW_SCUGIC_ID           XPAR_XSCUGIC_0_BASEADDR
  #elif defined(XPAR_PSU_ACPU_GIC_BASEADDR)
    #define HW_SCUGIC_ID           XPAR_PSU_ACPU_GIC_BASEADDR
  #else
    #error "platform_ids.h: no SCUGIC base address in xparameters.h."
  #endif
#else
  #define HW_SCUGIC_ID             XPAR_SCUGIC_0_DEVICE_ID
#endif

/*---------------------------------------------------------------------------
 * PS GPIO interrupt ID
 *
 * Classic BSPs export XPAR_XGPIOPS_0_INTR. Under SDT the interrupt number is
 * carried in the driver's own config structure (XGpioPs_Config::IntrId), which
 * is why HW_GPIOPS_INTR_ID() is a macro taking the config pointer rather than
 * a plain constant. Both flows go through the same call site in main.c.
 *---------------------------------------------------------------------------*/
#if defined(XPAR_XGPIOPS_0_INTR)
  #define HW_GPIOPS_INTR_ID(cfgptr)  XPAR_XGPIOPS_0_INTR
#elif defined(SDT)
  #define HW_GPIOPS_INTR_ID(cfgptr)  ((cfgptr)->IntrId)
#else
  #error "platform_ids.h: cannot determine PS GPIO interrupt ID."
#endif

/*---------------------------------------------------------------------------
 * LMK lock indicator pin.
 *
 * Bank 3 starts at absolute pin 78, so bank-3 bit 10 is pin 88. The baseline
 * configured direction on 0x88 (= 136, bank 4) while arming the interrupt on
 * bank 3 bit 10 -- a hex/decimal mix-up that left the two statements pointing
 * at different pins. VERIFY the intended MIO/EMIO pin against the block design.
 *---------------------------------------------------------------------------*/
#define HW_GPIOPS_BANK             XGPIOPS_BANK3
#define HW_LMK_LOCK_GPIO_BIT       10
#define HW_LMK_LOCK_GPIO_PIN       (78 + HW_LMK_LOCK_GPIO_BIT)

#endif /* SRC_PLATFORM_IDS_H_ */
